### ISSUE TITLE
All local import breaks after flattening the folder structure

### ISSUE THREAD

**Issue by kitgary** [ardanlabs/gotraining#64]
import (
   "github.com/ardanlabs/gotraining/13-http/api/app"
)

As the folder becomes http, the number prefix "13-" has to be removed, and all other imports as well.

**Comment by ardan-bkennedy** [comment]
Yes, I realized I forgot to make those changes. They are on my list for tonight !!!  Thanks

**Comment by ardan-bkennedy** [comment]
Fixed.

**Comment by kitgary** [comment]
Just a reminder, you forgot to fix the following files.

https://github.com/ardanlabs/gotraining/tree/9b2edb18351060de2278f42a93eceee802aefd7e/topics/concurrency_patterns
https://github.com/ardanlabs/gotraining/blob/9b2edb18351060de2278f42a93eceee802aefd7e/topics/testing/example4/handlers/handlers_test.go

Thanks

**Comment by ardan-bkennedy** [comment]
Thank You, Ugh.  What would I do without you? :)

**Comment by ardan-bkennedy** [comment]
Done
